config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  resources :staffs
  resources :reservattions
  resources :rooms
  resources :bills
  resources :tratments
  resources :doctors
  resources :room_types
  resources :departments
  resources :patients

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  belongs_to :patient
  belongs_to :tratment
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  belongs_to :department
  has_many :tratments
  has_many :patients, :through => :tratments
end

app/models/patient.rb
class Patient < ActiveRecord::Base
has_many :tratments
has_one :bill
has_many :doctors, :through => :tratments
has_one :reservattion
end

app/models/reservattion.rb
class Reservattion < ActiveRecord::Base
  belongs_to :patient
  belongs_to :room
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :room_type
  has_one :reservattion
end

app/models/room_type.rb
class RoomType < ActiveRecord::Base
has_many :rooms
has_many :staffs
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  belongs_to :room_type
end

app/models/tratment.rb
class Tratment < ActiveRecord::Base
  belongs_to :doctor
  belongs_to :patient
has_one :bill
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:Tratment_Amount, :room_amount, :total, :patient_id, :tratment_id)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:location, :Room_No, :room_type_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/reservattions_helper.rb
module ReservattionsHelper
end

app/helpers/room_types_helper.rb
module RoomTypesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/tratments_helper.rb
module TratmentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
  <div class="field">
    <%= f.label :Tratment_Amount %><br>
    <%= f.number_field :Tratment_Amount,class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :room_amount %><br>
    <%= f.number_field :room_amount,class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :total %><br>
    <%= f.number_field :total,class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :patient_id %><br>
    <%= f.text_field :patient_id,class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :tratment_id %><br>
    <%= f.text_field :tratment_id,class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bills</h1>

<table>
  <thead>
    <tr>
      <th>Tratment amount</th>
      <th>Room amount</th>
      <th>Total</th>
      <th>Patient</th>
      <th>Tratment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.Tratment_Amount %></td>
        <td><%= bill.room_amount %></td>
        <td><%= bill.total %></td>
        <td><%= bill.patient %></td>
        <td><%= bill.tratment %></td>
        <td><%= link_to 'Show', bill %></td>
        <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
        <td><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bill', new_bill_path %>

app/views/bills/new.html.erb
<h1>New Bill</h1>

<%= render 'form' %>

<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tratment amount:</strong>
  <%= @bill.Tratment_Amount %>
</p>

<p>
  <strong>Room amount:</strong>
  <%= @bill.room_amount %>
</p>

<p>
  <strong>Total:</strong>
  <%= @bill.total %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @bill.patient %>
</p>

<p>
  <strong>Tratment:</strong>
  <%= @bill.tratment %>
</p>

<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>