config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  resources :staffs
  resources :reservattions
  resources :rooms
  resources :bills
  resources :tratments
  resources :doctors
  resources :room_types
  resources :departments
  resources :patients

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  belongs_to :patient
  belongs_to :tratment
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  belongs_to :department
  has_many :tratments
  has_many :patients, :through => :tratments
end

app/models/patient.rb
class Patient < ActiveRecord::Base
has_many :tratments
has_one :bill
has_many :doctors, :through => :tratments
has_one :reservattion
end

app/models/reservattion.rb
class Reservattion < ActiveRecord::Base
  belongs_to :patient
  belongs_to :room
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :room_type
  has_one :reservattion
end

app/models/room_type.rb
class RoomType < ActiveRecord::Base
has_many :rooms
has_many :staffs
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  belongs_to :room_type
end

app/models/tratment.rb
class Tratment < ActiveRecord::Base
  belongs_to :doctor
  belongs_to :patient
has_one :bill
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:Tratment_Amount, :room_amount, :total, :patient_id, :tratment_id)
    end
end

app/controllers/room_types_controller.rb
class RoomTypesController < ApplicationController
  before_action :set_room_type, only: [:show, :edit, :update, :destroy]

  # GET /room_types
  # GET /room_types.json
  def index
    @room_types = RoomType.all
  end

  # GET /room_types/1
  # GET /room_types/1.json
  def show
  end

  # GET /room_types/new
  def new
    @room_type = RoomType.new
  end

  # GET /room_types/1/edit
  def edit
  end

  # POST /room_types
  # POST /room_types.json
  def create
    @room_type = RoomType.new(room_type_params)

    respond_to do |format|
      if @room_type.save
        format.html { redirect_to @room_type, notice: 'Room type was successfully created.' }
        format.json { render :show, status: :created, location: @room_type }
      else
        format.html { render :new }
        format.json { render json: @room_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /room_types/1
  # PATCH/PUT /room_types/1.json
  def update
    respond_to do |format|
      if @room_type.update(room_type_params)
        format.html { redirect_to @room_type, notice: 'Room type was successfully updated.' }
        format.json { render :show, status: :ok, location: @room_type }
      else
        format.html { render :edit }
        format.json { render json: @room_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /room_types/1
  # DELETE /room_types/1.json
  def destroy
    @room_type.destroy
    respond_to do |format|
      format.html { redirect_to room_types_url, notice: 'Room type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room_type
      @room_type = RoomType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_type_params
      params.require(:room_type).permit(:Price, :room_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/room_types_helper.rb
module RoomTypesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/tratments_helper.rb
module TratmentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/room_types/_form.html.erb
<%= form_for(@room_type) do |f| %>
  <% if @room_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room_type.errors.count, "error") %> prohibited this room_type from being saved:</h2>

      <ul>
      <% @room_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
  <div class="field">
    <%= f.label :Price %><br>
    <%= f.number_field :Price,class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :room_type %><br>
    <%= f.text_field :room_type,class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/room_types/edit.html.erb
<h1>Editing Room Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @room_type %> |
<%= link_to 'Back', room_types_path %>

app/views/room_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Room Types</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Room type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @room_types.each do |room_type| %>
      <tr>
        <td><%= room_type.Price %></td>
        <td><%= room_type.room_type %></td>
        <td><%= link_to 'Show', room_type %></td>
        <td><%= link_to 'Edit', edit_room_type_path(room_type) %></td>
        <td><%= link_to 'Destroy', room_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room type', new_room_type_path %>

app/views/room_types/new.html.erb
<h1>New Room Type</h1>

<%= render 'form' %>

<%= link_to 'Back', room_types_path %>

app/views/room_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @room_type.Price %>
</p>

<p>
  <strong>Room type:</strong>
  <%= @room_type.room_type %>
</p>

<%= link_to 'Edit', edit_room_type_path(@room_type) %> |
<%= link_to 'Back', room_types_path %>